language: php
php:
- '7.3'
- '7.4'
cache:
  directories:
  - $HOME/.composer/cache
install:
- composer install --prefer-source
script:
- ./vendor/bin/phpunit -v
after_success:
- if [ $TRAVIS_PHP_VERSION = '7.3' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh ./scripts/travisPublishDocs.sh; fi
- if [ $TRAVIS_PHP_VERSION = '7.3' ]; then sh ./scripts/publishCodeCoverage.sh; fi
env:
  global:
    secure: Jb3a0RxARfGJ5imt0zB0nouzK7b+FVcn/aYQNj0/L1OT26uDErK2Bsk7RI5kpETlz1z03/YsqlItRCU0XAN40UWjowopXSzb8LeyOqXXOPPFjm5rf5IL8br1L3axiwUg2S2Jq9IGdNcxoxKf/00qbyOWlJvuQ62LJCsGZvcHFI9U6JJ4VawZzB7/CcHAZFXkfsVfA7YQ73ueLccSy5a34MhaC81dl2fV0ad6ueEFJf486FK/39xxdutJCXOovnmhutri73yGZ2ShrmT86WlWvbILyOlsIKdzpMUOcaTStz2BJrwDdvlQs/iECY5xgiv4+nSkYmKYdlRqEkRbEC7eKt7eai66xmTSiUju8goaVtSEkpOm4Hjy21ehigdksjjNPaZcRZwqwKl9P45CX4b3OKQH2qdWQqv54WA8mkWxTdaY2yIOQr8s/sZH9SFliqydUUrxL6BrMEF0o2KShWTc7aFqUvCiEgbHe3s7t7Iv3aJDmn8F4E+nIOG2V7+MeAR07V3u7MkY316oRomVCDZWRPw33NE/bxkufr+C7XPjfSpmMSeZF74PYTJlovaVFahFw0C/5Cq1tVKS7ledJKw3haL6QTY44lqSUq+oOrTuNJHV94aRLGxduRkVrTfEPztp+QiPlWUPDal1Vnx6+6NpDx37qlXpfeUkSgiacYUkeeQ=
